name: "CI"
on:
  pull_request:
  push:
    branches: [main]
      
jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      
      - name: Install NIX
        uses: DeterminateSystems/nix-installer-action@v21
        
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
    
      - name: Flake check
        run: nix flake check
    
      - name: Run nixvim check
        run: nix build .#checks.x86_64-linux.nvim
    
      - name: Run pre-commit check
        run: nix build .#checks.x86_64-linux.pre-commit
    
      - name: Check Home Manager config
        run: |
          nix build .#homeConfigurations.syaikhu.activationPackage  